
create extension if not exists pgcrypto;

create table if not exists manutencoes (
  id bigint generated by default as identity primary key,
  categoria text not null check (categoria in ('frota','implementos','maquinas')),
  frota text,
  placa text,
  tipo text,
  identificacao text,
  placa_frota text,
  data_abertura date,
  nivel_critico text,
  motivo text,
  tipo_manutencao text,
  estabelecimento text,
  prev_liberacao date,
  prev_liberacao2 date,
  prev_liberacao3 date,
  dias_parado integer,
  dias_entrega integer,
  localizacao text,
  obs1 text,
  obs2 text,
  data_liberacao date,
  status text,
  sla text,
  categoria_origem text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists veiculos (
  placa text primary key,
  frota text,
  marca text,
  modelo text,
  tipo text,
  ano integer,
  documentacao text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists trg_manutencoes_updated_at on manutencoes;
create trigger trg_manutencoes_updated_at
before update on manutencoes
for each row execute function set_updated_at();

drop trigger if exists trg_veiculos_updated_at on veiculos;
create trigger trg_veiculos_updated_at
before update on veiculos
for each row execute function set_updated_at();

alter table manutencoes enable row level security;
alter table veiculos enable row level security;

drop policy if exists "public_read_manutencoes" on manutencoes;
create policy "public_read_manutencoes" on manutencoes
for select to anon using (true);

drop policy if exists "public_read_veiculos" on veiculos;
create policy "public_read_veiculos" on veiculos
for select to anon using (true);
